Ring of dueling/Ferox support added
PTYB/OpenAbyss pull request #9
Opened 2022-02-12 21:50 UTC by okazakikun

Added support for ring of dueling teleport + using the pool to restore health and stamina, helpful for ironmen to save food/energy pots.

2022-02-13 04:24 UTC, PTYB requested changes

2022-02-22 18:15 UTC, okazakikun commented on src/com/open/abyss/Constants.kt
> +    const val ITEM_RING_OF_DUELING = "Ring of dueling(8)"
Used in WithdrawEquipRing.kt

2022-02-22 18:15 UTC, okazakikun commented on src/com/open/abyss/branch/BankOpenedBranches.kt
> +class ShouldWithdrawRing(script: Script) : Branch<Script>(script, "Withdraw Ring of dueling?") {
Fixed the naming of the class to reflect the actions within it better

2022-02-22 18:16 UTC, okazakikun commented on src/com/open/abyss/leaf/FeroxRestore.kt
> +//    private fun walkToPool(pool: GameObject){
removed

2022-02-22 18:17 UTC, okazakikun commented on src/com/open/abyss/leaf/bankopened/WithdrawEquipRing.kt
> +        ring.interact("Wear")
added validation of withdraw and of equip

2022-02-22 18:55 UTC, okazakikun commented on src/com/open/abyss/branch/BankOpenedBranches.kt
> +        return Equipment.stream().id(*Constants.ID_RING_OF_DUELING).first().name().isEmpty()
changed to checking if Item.Nil

2022-02-22 19:07 UTC, PTYB commented on src/com/open/abyss/leaf/FeroxRestore.kt
> +            if (pool.inViewport()) {
Can join if statement.above and remove the extra else(Or all 3 statements since they do the same thing)

2022-02-22 19:07 UTC, PTYB commented on src/com/open/abyss/leaf/LeaveFerox.kt
> +        if (barrier.inViewport()) {
Le join

2022-02-22 19:07 UTC, PTYB commented on src/com/open/abyss/leaf/LeaveFerox.kt
> +        val barrier = Objects.stream().type(GameObject.Type.INTERACTIVE).name("Barrier").at(TILE_FEROX_BARRIER).first()
Can use objects.stream(Tile,type) Or something like that with distance.

2022-02-22 19:54 UTC, PTYB approved these changes

2022-02-22 19:54 UTC, merged